---

- hosts : all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache2 and php packages on web servers
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }} "
      state: latest

  - name: copy index html file for site
    tags: apache,apache2
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  tags: db,mariadb,ubuntu
  become: true
  tasks:

  - name: install mariadb on db servers
    package:
      name:
        - "{{ mariadb_package }}"
      state: latest

- hosts: file_servers
  tags: samba,ubuntu
  become: true
  tasks:

  - name: install samba package
    package:
      name:
        - "{{samba_package}}"
      state: latest

